<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatosEsencialesSeeder extends Seeder
{
    public function run()
    {
        // Usuarios
        DB::table('users')->insert([
            [
                'id' => 4,
                'name' => 'Admin',
                'last_name' => 'Admin',
                'email' => 'admin@yopmail.com',
                'password' => Hash::make('12345678'),
                'phone' => 'Admin',
                'role' => 'admin',
                'created_at' => '2025-05-10 05:25:58',
                'updated_at' => '2025-05-10 05:25:58',
            ],
            [
                'id' => 9,
                'name' => 'Juan',
                'last_name' => 'Pérez',
                'email' => 'juanp@yopmail.com',
                'password' => Hash::make('password123'),
                'phone' => '3001234567',
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Ana',
                'last_name' => 'Gómez',
                'email' => 'anag@yopmail.com',
                'password' => Hash::make('password123'),
                'phone' => '3002345678',
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Carlos',
                'last_name' => 'López',
                'email' => 'carlosl@yopmail.com',
                'password' => Hash::make('password123'),
                'phone' => '3003456789',
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'María',
                'last_name' => 'Sánchez',
                'email' => 'marias@yopmail.com',
                'password' => Hash::make('password123'),
                'phone' => '3004567890',
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Luis',
                'last_name' => 'Ramírez',
                'email' => 'luisr@yopmail.com',
                'password' => Hash::make('password123'),
                'phone' => '3005678901',
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'Lucía',
                'last_name' => 'Mora',
                'email' => 'luciam@yopmail.com',
                'password' => Hash::make('password123'),
                'phone' => '3006789012',
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'Pedro',
                'last_name' => 'Martínez',
                'email' => 'pedrom@yopmail.com',
                'password' => Hash::make('password123'),
                'phone' => '3007890123',
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'Laura',
                'last_name' => 'Hernández',
                'email' => 'laurah@yopmail.com',
                'password' => Hash::make('password123'),
                'phone' => '3008901234',
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'Javier',
                'last_name' => 'García',
                'email' => 'javierg@yopmail.com',
                'password' => Hash::make('password123'),
                'phone' => '3009012345',
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'Clara',
                'last_name' => 'Fernández',
                'email' => 'claraf@yopmail.com',
                'password' => Hash::make('password123'),
                'phone' => '3000123456',
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Empresas
        DB::table('empresas')->insert([
            [
                'id' => 1,
                'nombre' => 'Sobusa',
                'descripcion' => 'Sobusa es una empresa dedicada al transporte público urbano, conectando diversas zonas de la ciudad con eficiencia.',
                'imagen' => 'sobusa.jpeg',
                'created_at' => '2025-04-27 00:12:04',
                'updated_at' => '2025-05-11 04:35:43',
            ],
            [
                'id' => 2,
                'nombre' => 'Alianza Sodis',
                'descripcion' => 'Alianza Sodis se destaca por su puntualidad y servicio de calidad, ofreciendo rutas cómodas para todos.',
                'imagen' => 'sodis.jpeg',
                'created_at' => '2025-04-27 00:12:32',
                'updated_at' => '2025-05-11 04:35:44',
            ],
            [
                'id' => 3,
                'nombre' => 'Coolitoral',
                'descripcion' => 'Coolitoral ofrece una alternativa moderna y rápida para moverse por las zonas costeras de la ciudad.',
                'imagen' => 'colitoral.jpeg',
                'created_at' => '2025-04-27 00:12:39',
                'updated_at' => '2025-05-11 04:35:44',
            ],
            [
                'id' => 4,
                'nombre' => 'La Carolina',
                'descripcion' => 'La Carolina conecta los barrios del suroccidente con el centro, garantizando seguridad y eficiencia.',
                'imagen' => 'carolina.jpeg',
                'created_at' => '2025-04-27 00:12:44',
                'updated_at' => '2025-05-11 04:35:44',
            ],
        ]);

        // Comentarios
        DB::table('comentarios')->insert([
            [
                'id' => 31,
                'user_id' => 9,
                'content' => 'Me parece excelente la iniciativa de SostiTrans, las rutas están bien distribuidas y la app funciona muy bien. ¡Muy útil!',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 32,
                'user_id' => 9,
                'content' => 'Sería genial si se pudieran agregar más paradas en algunas zonas menos cubiertas. Pero en general, es una herramienta muy útil.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 33,
                'user_id' => 10,
                'content' => 'SostiTrans me ha facilitado mucho la planificación de mis viajes. La visualización en tiempo real de los buses es una gran ventaja.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 34,
                'user_id' => 10,
                'content' => 'Una sugerencia: agregar más información sobre la ocupación de los buses para que podamos tomar decisiones más informadas.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 35,
                'user_id' => 11,
                'content' => 'Es una aplicación muy intuitiva, y las rutas están bastante bien definidas. Me encanta que se pueda ver la información en tiempo real.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 36,
                'user_id' => 11,
                'content' => 'Una mejora que me gustaría ver es la opción de recibir alertas en caso de retrasos importantes en las rutas.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 37,
                'user_id' => 12,
                'content' => 'El mapa interactivo es de gran ayuda, especialmente cuando no conozco bien la ciudad. ¡SostiTrans ha sido una gran ayuda!',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 38,
                'user_id' => 12,
                'content' => 'Me gustaría que los horarios de los buses se actualizaran un poco más rápido, ya que a veces parece que hay retrasos que no se reflejan.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 39,
                'user_id' => 13,
                'content' => 'SostiTrans es una excelente herramienta para organizar mis rutas diarias. El mapa interactivo es muy preciso y la información de las rutas es clara.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 40,
                'user_id' => 13,
                'content' => 'Me gustaría que la app incluyera la opción de ver el nivel de contaminación de los buses en tiempo real. Sería interesante poder tomar decisiones más sostenibles.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 41,
                'user_id' => 14,
                'content' => 'SostiTrans ha mejorado mi experiencia con el transporte público. Ahora puedo planificar mejor mis desplazamientos y ver en qué momento llega el bus.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 42,
                'user_id' => 14,
                'content' => 'Sería útil poder filtrar las rutas por tipo de bus (por ejemplo, si son buses ecológicos o tienen algún servicio especial).',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 43,
                'user_id' => 15,
                'content' => 'SostiTrans ha transformado la forma en que me muevo por la ciudad. El mapa interactivo y la visualización de rutas en tiempo real son muy útiles.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 44,
                'user_id' => 15,
                'content' => 'Una sugerencia sería tener más detalles sobre las rutas de cada empresa, como el tiempo estimado de llegada y las paradas intermedias.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 45,
                'user_id' => 16,
                'content' => 'Me encanta la opción de ver las rutas de buses en el mapa. Es muy fácil de usar y me ahorra tiempo. ¡Excelente aplicación!',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 46,
                'user_id' => 16,
                'content' => 'Me gustaría que se pudieran agregar más detalles sobre las rutas, como el tipo de bus o la accesibilidad para personas con movilidad reducida.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 47,
                'user_id' => 17,
                'content' => 'La visualización en tiempo real de los buses es una de las mejores características de SostiTrans. Me ha ayudado a llegar a tiempo a mis citas.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 48,
                'user_id' => 17,
                'content' => 'Sería útil poder ver la información sobre el tráfico en tiempo real, así sabría si debo tomar una ruta alternativa si hay congestión.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 49,
                'user_id' => 18,
                'content' => 'SostiTrans ha facilitado mi vida diaria. Ahora puedo organizar mis viajes de manera eficiente, gracias a la información clara de las rutas.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
            [
                'id' => 50,
                'user_id' => 18,
                'content' => 'Me gustaría que la app permitiera hacer reservas para el bus, de modo que siempre haya espacio disponible para los usuarios.',
                'created_at' => '2025-05-10 08:40:15',
                'updated_at' => '2025-05-10 08:40:15',
            ],
        ]);
    }
}
